### ISSUE TITLE
Create and review a Performance document workflow diagram

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#145]
Things to add:

a) Who will do the CIM2 classes
b) How will it connect to simulations
c) How will it connect to platform
d) Who needs to review etc

**Comment by davidhassell** [comment]
![performance_workflow_v1](https://cloud.githubusercontent.com/assets/8126576/16914788/0fbf68a2-4cec-11e6-898f-aaac24cfbc37.png)
Instead of catching a Performance document per simulation, create a new CIM2 **Average Performance** document which is applicable to every ensemble member. It is still possible to create individual performances for particular ensemble members, but I don't think that we need a workflow for this right now. (The **Machine** workflow will look very similar to this.)

**Comment by davidhassell** [comment]
Here is a first draft of a Machine and Performance collection spreadsheet:

https://docs.google.com/spreadsheets/d/1s6Xjl8vUvxifyojk_YpSwgvrJ2sfCwK5VhT9KfPnpLI/edit#

There is one tab for the machine and one for the performance. The Performance tab allows for selecting which experiments the performance applies to.

If more than one Performance is required for a given machine, then the Performance tab can be copied (?)

**Comment by davidhassell** [comment]
This was discussed on 2017-07-18 and thought to be OK (see note at top of draft spreadsheet). It will be revisited in September 2017 when we expect to implement it
