### ISSUE TITLE
Display standard properties in the Viewer

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#91]
WHO: ESPS

This is the list of standard properties that must be displayed in the Model Component view for the ESPS project:
1. couplingFramework
2. shortName (you already use this)
3. longName (you already use this)
4. description (you already use this)
5. license
6. responsibleParty (you already use this?)
7. releaseDate
8. previousVersion
9. fundingSource
10. citation (you already use this)
11. onlineResource
12. componentLanguage
13. grid (this would be better off being shown in it's own tab)
14. type (you already use this?)
15. timing
16. documentAuthor (you already use this?  but I'm not sure how it's different from responsibleParty)
17. documentCreationDate

The following items need to be displayed from CIM 1.10. Ticket #92 must be completed first. 
1. codeAccess
2. version

**Comment by momipsl** [comment]
These have all been added to the viewer.

**Comment by murphysj** [comment]
I have verified that the following properties ARE NOW showing up in the viewer
1) type

The following properties ARE NOT showing up
1) CodeAccess
2) Version
3) License

I can not test the following properties because we have no instance with them in it. I will create a test instance with some of these. 
1) onlineResource, unless this is a sub-part to a citation, in which case they are showing up as "location". 
2)documentAuthor
3)timing
4)grid
5)previousVersion
6)couplingFramework

I have verified that the following properties are STILL showing up in the Viewer (were already implemented)

1) long_name
2) short_name (appears as name)
3) description
4) funding source (appears as funder)
5) citations
6) componentLanguage (appears as language)
7) responsibleParty (shows up as Contact, PI, etc)
8) documentCreationDate (shows up as doc.created)
9) releaseDate

**Comment by momipsl** [comment]
Latest release should resolve this but I do not see any published documents with the full set of properties to be able to verify 100%

**Comment by allynt** [comment]
Thanks for this Mark.  I can see that the new CIM 1.10 properties are 
being rendered.

Cheers,
Allyn

On 07/26/2015 02:52 PM, Mark A. Greenslade wrote:
>
> Latest release should resolve this but I do not see any published 
> documents with the full set of properties to be able to verify 100%
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/91#issuecomment-125038332>.
>

-- 
Allyn Treshansky
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305 USA
Email: allyn.treshansky@noaa.gov
Phone: +1 303-497-7734

**Comment by murphysj** [comment]
I have verified that the following properties ARE NOW showing up in the viewer
1) Version
2) Type (but formatted incorrectly)
3) CodeAccess

The following properties ARE NOT showing up
1) License

I can not test the following properties because we have no instance with them in it. I will create a test instance with some of these.
1) onlineResource, unless this is a sub-part to a citation, in which case they are showing up as "location".
2)documentAuthor (ESPS/HYCOM republished with this)
3)timing
4)grid
5)previousVersion
6)couplingFramework (ESPS/HYCOM republished with this)

I have verified that the following properties are STILL showing up in the Viewer (were already implemented)

1) long_name
2) short_name (appears as name)
3) description
4) funding source (appears as funder)
5) citations
6) componentLanguage (appears as language)
7) responsibleParty (shows up as Contact, PI, etc)
8) documentCreationDate (shows up as doc.created)
9) releaseDate

**Comment by momipsl** [comment]
Actually there are no documents with a valid license description.  You will need to chase this up with Allyn.

Regarding a test instance with other properties please notify when available.

**Comment by murphysj** [comment]
License is now showing up. closing.
