### ISSUE TITLE
Enable NOAA to be able to control / modify project ingestion

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#95]
It might be nice to enable Allyn to change the cron status for NOAA-based projects, to be able to trouble shoot issues etc so Mark does not need to do this himself all the time. 

Not sure what that would entail.

**Comment by allynt** [comment]
In theory, I can already do this.  I have access to the server and I can view/edit the crontab.  In practice, I think what this ticket is asking for is to be able to set the ingestion interval on a per-project basis.

**Comment by murphysj** [comment]
would you have had the appropriate know-how to figure out the CAM ingestion
problem? It is not just server access I am thinking we need, but some
cross-tasker training.

On Mon, Feb 9, 2015 at 11:33 AM, allynt <notifications@github.com> wrote:

> In theory, I can already do this. I have access to the server and I can
> view/edit the crontab. In practice, I think what this ticket is asking for
> is to be able to set the ingestion interval on a per-project basis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/95#issuecomment-73562768>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
I am looking at the ingestion log and I can see the following sort of message:

ES-DOC INFO ** > INGEST ERROR :: Processing ID = 4 :: Doc ID = f158d460-b3e7-4db4-ad37-e5a1e22107a3 :: Doc Version = 2 :: Institute code is unsupported: Department of Energy :: <type 'exceptions.ValueError'>

This identifies the problem.  I would not have known how to fix the problem though.

(Bear in mind, though, that hindsight is 20/20.)

**Comment by momipsl** [comment]
The document ingestion and indexation jobs have been cronified.  All NOAA has to do is publish documents to their feeds.

**Comment by momipsl** [comment]
The esdoc-shell has been extended with a new command: esdoc-api-db-insert-project which allows admin to add a new project tot he database from the command line.  This is a pre-requisite to ingesting the documents from that project.

Document ingestion has been refined so that only documents belonging to a single project can be ingested - this speeds up ingestion dramatically.  To specifiy a single project the operator needs simply to edit the [pyesdoc.conf](https://raw.githubusercontent.com/ES-DOC/esdoc-shell/master/resources/deployment/template-pyesdoc.conf) file.

**Comment by murphysj** [comment]
@allynt 

please test.

**Comment by murphysj** [comment]
@allynt 

What was the result of your test. Can we do this now?

**Comment by allynt** [comment]
I have been unable to do this.  But I think it is b/c of a lack of 
understanding about how to use the esdoc-shell, rather than a bug on his 
part.  Do you know when Mark returns so that I can ask him about this?

Allyn

On 08/25/2015 03:16 PM, Sylvia Murphy wrote:
>
> @allynt <https://github.com/allynt>
>
> What was the result of your test. Can we do this now?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/95#issuecomment-134744258>.
>

-- 
Allyn Treshansky
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305 USA
Email: allyn.treshansky@noaa.gov
Phone: +1 303-497-7734

**Comment by momipsl** [comment]
@allynt  Let's setup a welsher session together so that I can run you through the process.

**Comment by murphysj** [comment]
Was this ever resolved?

**Comment by momipsl** [comment]
This was IMHO resolved.  The workflow for adding a new project is as follows:

1.  Using esdoc-shell: esdoc-api-db-add-project PROJECT-NAME

2.  Update $ESDOC_HOME/ops/conf/pyesdoc.conf: add new project ATOM feed section.

3.  Update $ESDOC_HOME/ops/conf/api.conf: set project code accordingly.

**Comment by momipsl** [comment]
Note that this will be covered in a training session when I come to Boulder.

**Comment by murphysj** [comment]
Ok, I'll close this ticket.
